//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./account_types');
//HELPER FUNCTIONS AND STRUCTURES

var AccountCreationService_createAccount_args = function(args) {
  this.createAccountRequest = null;
  if (args) {
    if (args.createAccountRequest !== undefined && args.createAccountRequest !== null) {
      this.createAccountRequest = new ttypes.CreateAccountRequest(args.createAccountRequest);
    }
  }
};
AccountCreationService_createAccount_args.prototype = {};
AccountCreationService_createAccount_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.createAccountRequest = new ttypes.CreateAccountRequest();
        this.createAccountRequest.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AccountCreationService_createAccount_args.prototype.write = function(output) {
  output.writeStructBegin('AccountCreationService_createAccount_args');
  if (this.createAccountRequest !== null && this.createAccountRequest !== undefined) {
    output.writeFieldBegin('createAccountRequest', Thrift.Type.STRUCT, 1);
    this.createAccountRequest.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AccountCreationService_createAccount_result = function(args) {
  this.success = null;
  this.userAlreadyExistException = null;
  if (args instanceof ttypes.UserAlreadyExistException) {
    this.userAlreadyExistException = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.AccountCreatedResponse(args.success);
    }
    if (args.userAlreadyExistException !== undefined && args.userAlreadyExistException !== null) {
      this.userAlreadyExistException = args.userAlreadyExistException;
    }
  }
};
AccountCreationService_createAccount_result.prototype = {};
AccountCreationService_createAccount_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.AccountCreatedResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.userAlreadyExistException = new ttypes.UserAlreadyExistException();
        this.userAlreadyExistException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AccountCreationService_createAccount_result.prototype.write = function(output) {
  output.writeStructBegin('AccountCreationService_createAccount_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.userAlreadyExistException !== null && this.userAlreadyExistException !== undefined) {
    output.writeFieldBegin('userAlreadyExistException', Thrift.Type.STRUCT, 1);
    this.userAlreadyExistException.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AccountCreationServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
AccountCreationServiceClient.prototype = {};
AccountCreationServiceClient.prototype.seqid = function() { return this._seqid; };
AccountCreationServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

AccountCreationServiceClient.prototype.createAccount = function(createAccountRequest, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_createAccount(createAccountRequest);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_createAccount(createAccountRequest);
  }
};

AccountCreationServiceClient.prototype.send_createAccount = function(createAccountRequest) {
  var output = new this.pClass(this.output);
  var params = {
    createAccountRequest: createAccountRequest
  };
  var args = new AccountCreationService_createAccount_args(params);
  try {
    output.writeMessageBegin('createAccount', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

AccountCreationServiceClient.prototype.recv_createAccount = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AccountCreationService_createAccount_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.userAlreadyExistException) {
    return callback(result.userAlreadyExistException);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('createAccount failed: unknown result');
};
var AccountCreationServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
AccountCreationServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
AccountCreationServiceProcessor.prototype.process_createAccount = function(seqid, input, output) {
  var args = new AccountCreationService_createAccount_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.createAccount.length === 1) {
    Q.fcall(this._handler.createAccount.bind(this._handler),
      args.createAccountRequest
    ).then(function(result) {
      var result_obj = new AccountCreationService_createAccount_result({success: result});
      output.writeMessageBegin("createAccount", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      if (err instanceof ttypes.UserAlreadyExistException) {
        result = new AccountCreationService_createAccount_result(err);
        output.writeMessageBegin("createAccount", Thrift.MessageType.REPLY, seqid);
      } else {
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("createAccount", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.createAccount(args.createAccountRequest, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.UserAlreadyExistException) {
        result_obj = new AccountCreationService_createAccount_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("createAccount", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("createAccount", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
