//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

AccountCreationService_createAccount_args = function(args) {
  this.createAccountRequest = null;
  if (args) {
    if (args.createAccountRequest !== undefined && args.createAccountRequest !== null) {
      this.createAccountRequest = new CreateAccountRequest(args.createAccountRequest);
    }
  }
};
AccountCreationService_createAccount_args.prototype = {};
AccountCreationService_createAccount_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.createAccountRequest = new CreateAccountRequest();
        this.createAccountRequest.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AccountCreationService_createAccount_args.prototype.write = function(output) {
  output.writeStructBegin('AccountCreationService_createAccount_args');
  if (this.createAccountRequest !== null && this.createAccountRequest !== undefined) {
    output.writeFieldBegin('createAccountRequest', Thrift.Type.STRUCT, 1);
    this.createAccountRequest.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AccountCreationService_createAccount_result = function(args) {
  this.success = null;
  this.error = null;
  if (args instanceof UserAlreadyExist) {
    this.error = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new AccountCreatedResponse(args.success);
    }
    if (args.error !== undefined && args.error !== null) {
      this.error = args.error;
    }
  }
};
AccountCreationService_createAccount_result.prototype = {};
AccountCreationService_createAccount_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new AccountCreatedResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.error = new UserAlreadyExist();
        this.error.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AccountCreationService_createAccount_result.prototype.write = function(output) {
  output.writeStructBegin('AccountCreationService_createAccount_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.error !== null && this.error !== undefined) {
    output.writeFieldBegin('error', Thrift.Type.STRUCT, 1);
    this.error.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AccountCreationServiceClient = function(input, output) {
  this.input = input;
  this.output = (!output) ? input : output;
  this.seqid = 0;
};
AccountCreationServiceClient.prototype = {};

AccountCreationServiceClient.prototype.createAccount = function(createAccountRequest, callback) {
  this.send_createAccount(createAccountRequest, callback); 
  if (!callback) {
    return this.recv_createAccount();
  }
};

AccountCreationServiceClient.prototype.send_createAccount = function(createAccountRequest, callback) {
  var params = {
    createAccountRequest: createAccountRequest
  };
  var args = new AccountCreationService_createAccount_args(params);
  try {
    this.output.writeMessageBegin('createAccount', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_createAccount();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

AccountCreationServiceClient.prototype.recv_createAccount = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new AccountCreationService_createAccount_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.error) {
    throw result.error;
  }
  if (null !== result.success) {
    return result.success;
  }
  throw 'createAccount failed: unknown result';
};
